### ISSUE TITLE
Customization Options

### ISSUE THREAD

**Issue by otymartin** [Chakery/HUD#1]
@Chakery 

Love this library - works great.

Would like to be able to customize to better blend with my UI austhetics.
Eg. `Background color`, `font`, `opacity` and perhaps even a `customer image` for resulting cases `Error` `Success` `Background dimming` etc

**Comment by chakery** [comment]
@otymartin

Thx for your use and support for HUD.
I will consider your proposed, but  I'm very busy now,  or you can pull request for me.

**Comment by otymartin** [comment]
@Chakery 
Would love to pull request but im new to swift & programming in general :(
