### ISSUE TITLE
This is not for swift 4.0

### ISSUE THREAD

**Issue by SumeetMourya** [Chakery/HUD#4]
Are you still supporting this?

**Comment by aifedorov** [comment]
Hi, 9SumeetMourya!
You can try it:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end
```
This makes Xcode build all your pods with Swift 3.2.

**Comment by chakery** [comment]
you can use version 2.0.1, see[ README](https://github.com/Chakery/HUD/blob/master/README.md) for details.
